### PR TITLE
fix: workspace members affect --dry-run estimation

### LINKED ISSUE #14: Dry run command gives wrong result
When I ran `cargo clean-recursive --dry-run`, it claimed 1.5 TB space will be saved. But that's even more than my 1 TB SSD can hold in total.

When I then ran `cargo clean-recursive`, 152.3 GB was actually saved.

Maybe it's a unit conversion error?

### PR DESCRIPTION
**Pull request by theammir**
Currently, `cargo clean-recursive --dry-run` spawns a `cargo clean` child in each crate subdirectory of a project folder. In reality, cleaning a workspace member without a specified `--package` is no different from cleaning its workspace root.
In `--dry-run`, this makes any workspace estimate significantly more space usage.

[The Cargo Book](https://doc.rust-lang.org/cargo/reference/workspaces.html) defines a workspace as a directory with a `[workspace]` section in its `Cargo.toml`, while workspace members don't have their own `Cargo.lock`.

We could opt out of cleaning any children of a workspace root (at least for accurate `--dry-run`), however, we also have to address the `exclude` field (subdirectories can be standalone crates).

One solution is to check for both `Cargo.toml` and `Cargo.lock`, since standalone crates with no `Cargo.lock` were arguably not built yet.
There is now a possibility of a false negative if a crate is missing its lock file for some reason.

With all that said, this PR should resolve #14, although more testing is needed.

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -14,7 +14,7 @@ const DEFAULT_SKIP_DIR_NAMES: [&str; 3] = [".git", ".rustup", ".cargo"];
 
 fn main() -> Result<()> {
     let mut args = args();
-    if let Some("clean-recursive") = std::env::args().skip(1).next().as_deref() {
+    if let Some("clean-recursive") = std::env::args().nth(1).as_deref() {
```
Comment (IgaguriMK) [inline src/main.rs]: As a general rule, please separate refactoring into separate commits.
(This code has been fixed in master, so please delete this from this PR.)

**Review by IgaguriMK — CHANGES_REQUESTED** [review]
I checked the code.
I modified some of the code in a different way. I will merge it excluding the refactoring parts.
